### ISSUE TITLE
EGIS.Controls nuget packages throw exceptioin on net6.0 winform

### ISSUE THREAD

**Issue by cyberpd** [wfletcher/EasyGIS.NET#100]
Can I use EGIS nuget packages on net6.0  winform?

test nuget package
 - EGIS.Controls (https://www.nuget.org/packages/EGIS.Controls/4.8.4)
 - EGIS.ShapeFileLib (https://www.nuget.org/packages/EGIS.ShapeFileLib/4.8.4)
 - EGIS.Projections  (https://www.nuget.org/packages/EGIS.Projections/4.8.4)

### Environment
- Tool : Visual Studio 2022 Pro. 17.4.1
- Map : my custom maps base on openstreetmap. world.shp,  world.prj, ...
- project 'TestNet47' target framework :  .net 4.7.2 
- project 'TestNet6'  target framework : .net 6.0

### Test1

project 'TestNet47' excution succeeds.

### Test2

project 'TestNet6' excution fails.

``` c#
public TestNet6Form()
{
    InitializeComponent();

    EGIS.Controls.SFMap sfMap1 = new EGIS.Controls.SFMap();
    sfMap1.ClearShapeFiles();
    sfMap1.AddShapeFile("./MapData/world.shp", "world", ""); // throw System.AccessViolationException
    sfMap1.Refresh();
}
```

System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

### Test Code

[TestEGIS.zip](https://github.com/wfletcher/EasyGIS.NET/files/10129389/TestEGIS.zip)

**Comment by wfletcher** [comment]
there seems to be a bug. Appears to be working if targeting x86 but not x64. Will investigate and get back to you

**Comment by wfletcher** [comment]
It appears that something has changed internally in the proj9_0 native dll.
The AccessViolationException is generated when calling proj_trans_generic in Proj6Native.cs and seems to do with the way the runtime marshaler calls external native functions. 

Adding **SetLastError=true** to the DllImport function has fixed the issue

```
[DllImport(ProjDllName, CallingConvention = CallingConvention.Cdecl, SetLastError = true)]
        public static extern unsafe int proj_trans_generic(
```

What is frustrating about this bug is that it does not affect .NET4.7 Framework and when compiled for .NET6 it only throws the AccessViolationException in the Release build when running as 64bit.

**Comment by wfletcher** [comment]
new 4.8.5 nuget packages published which fix this issue
