### ISSUE TITLE
When will the multipoint Createwriter be supported?

### ISSUE THREAD

**Issue by EQusJin** [wfletcher/EasyGIS.NET#104]
I am trying to create a multipoint type shape file using the CreateWriter function.

But no multipoint entry in CreateWriter case statement

Are you planning to support this?

Or is there any other way to create the type of multipoint shapefiles?

thank you

**Comment by wfletcher** [comment]
Currently only the most common Shape types are supported - polyline, point, polygon and polylineM.

There is also another request for adding polylineZ shape types. If I get time I will try and add support for these shape types, but for the moment as a workaround you may need to add your points in each multipoint record as separate point records

**Comment by dusko23** [comment]
In the real world, Multipoint does not exist. Each point has its own properties. In the real world, there are differences in data beyond coordinates. 100%. Even if PointM appears to be fine at the beginning, sooner or later it becomes evident that separation at the dbf level is needed. 
Why Esri created the Multipoint shape file feels weird?  However, because of dbf 2GB limit PointM shape type could save the day in some rare situations.
If Esri would consider supporting Sqlite DB in the shape file family the Gis world would be a better place. Instead Esri "invented" Geodatabase in the flavor of Access and SQLite database. I doubt if a "normal" Gis developer is able to understand why Access is needed. Sure, from the pricing and "richness" point of view, Esri's biodiversity of Geodatabase is understandable.
Replacing the dbf file as an integral part of the shapefile with SQLite DB would correct the long-lasting issue. Converting Sqlite DB to DBF conversion is easy if dbf is needed whatever the reason.
Last but not least, Esris' concept to overcome shape file dbf problems by introducing Geodatabase is the wrong one. The Geodatabase domain is a **gis project** not the **individual shape file**.

**Comment by wfletcher** [comment]
Firstly a MultiPoint shape type is not the same as a PointM shape type - the first type contains multiple points per record, while a PointM record contains a single point with a measure value. Saying that a multipoint does not exist in the real world is like saying that a polygon shape type should only contain single polygons per record, yet they can contain multiple polygons per record and this is quite valid. As an example -  a polygon shapefile representing the countries of the world may contain multiple polygons per record representing the "islands" of a country, but there is only one set of attributes for the polygons in the dbf records. I am sure there are similar examples for the need for a multipoint spatial type. The shapefile specification contains a MultiPoint shape type so this request is valid.

As for your comments on Sqlite as a replacement for the DBF you need to remember that the shapefile was created before databases supported spatial field types and the geodatabase was probably an interim solution before spatial field types were supported in all modern databases. If you are interested in using sqllite for GIS functionality I would recommend looking at spatiallite https://en.wikipedia.org/wiki/SpatiaLite

**Comment by dusko23** [comment]
Thank you for your comments, Winston.
Sorry for the Multipoint shape and PointM confusion. It is a Multipoint shape file I am referring to.
 I forgot to mention that there are two views on GIS. CAD view and real world view. The mixture also exists.

Comparison of polygons vs multipoint is acceptable from a CAD point of view.  In the real world, such a comparison does not seem right.
The thing is that Point is a real-world spatial entity that has no dimension, just a coordinate.  But that point represents a real point that is very much different from a point nearby. Attribute-wise as well.
The Shapefile of countries of the world is CAD type of view.

In reality Countries of the world is a collection of individual real-world countries. Each country can have multiple records for a single dbf value. Holes in polygons are actual representations of a spatial entity that has holes. Unless someone is interested in holes as such (area for example) one dbf record for multi-record is fine and it is real-world compatible.
I agree there are MultiPoint shape file examples. But that is a CAD type of geometry. Supporting that is fine.

I am aware that shape file was born before Sqlite took place. However, at least in my opinion, Esri should consider introducing a Sqlite type of DBF long ago. Instead, an interim solution was offered.  That is **constant process replacement** instead of **constant process improvement**. Shp file is massively used for spatial data exchange. And that is a problem.

I have been using your excellent library for many years now and will be releasing search and rescue software this year. I might be biased by writing all kinds of real-world applications for decades.  But I am using your library from a real-world perspective.
In the past, I did test Gaia and underlying spatiality. It is an excellent tool. But somehow I felt that sooner or later I would have problems using it. While your library is just perfect for what I am up to. I believe that after my software is released it will demonstrate another perception of using gis.
