### ISSUE TITLE
Calculating Distances

### ISSUE THREAD

**Issue by dusko23** [wfletcher/EasyGIS.NET#108]
I have checked calculating distances and it appears that there might be a problem in the library.
I have created a pdf document in order to present the problem in a concise and simple way.
I have triple-checked for any errors in my code. None was found. Even after cross-checking.
[CoodinateConverisonQuestion.pdf](https://github.com/wfletcher/EasyGIS.NET/files/10711293/CoodinateConverisonQuestion.pdf)

**Comment by dusko23** [comment]
I did not find an option on how to calculate the distance on the ellipsoid.
The coordinate-sharp library returns the correct result for the pdf example.
This library has the option to use either Harvesine (big circle calculation) or ellipsoidal one (probably based on the Vincety formula).
![image](https://user-images.githubusercontent.com/26789352/218252592-60d5a73d-0e39-41f2-af6e-09263503c167.png)
411386 meters

**Comment by wfletcher** [comment]
My library is currently using the Haversine formula for the distance calculations, which only uses a sphere model rather than the ellipsoid. 

Note that in the PDF document you uploadedthe exaple (below) is actually not using the haversine calculation - that is the ST_DistanceSphere function. https://postgis.net/docs/ST_DistanceSphere.html

![image](https://user-images.githubusercontent.com/12992602/218255982-95b3c86f-ed7b-4b6e-adc4-92a237721f8b.png)

I am currently looking at the Vincenty formula which is more accurate. The function appears to be giving the same results as your pdf document and I am also verifying it against SqlServer STDistance function, which I believe is the same as the Postgis ST_DistanceSpheroid function

**Comment by dusko23** [comment]
That sounds good. I can see a bug in the above example now.
I am using Wgs84 distance calculations throughout my program.
The thing is that I support concurrent multiple EPSG shape files where the underlying raster map can have yet another EPSG. 100% tutti-frutti. 
The only reasonable way to calculate the distance between any mixture of shapefile points is to use ellipsoidal distance.
Therefore classical Pythagorean formula does not work for me.
Using great circle calculations introduces a big discrepancy when switching between web tiles a local projected maps.
On-the-fly conversion on mouse move (including proximity detection of any of the existing points) is very good.
I am just curious how you manage to draw/detect that fast a shape file where EPSG differs from an SFmap object.
That really amazes me :-).
