### ISSUE TITLE
ZOOM and PAN Simultaneously ISSUE

### ISSUE THREAD

**Issue by dusko23** [wfletcher/EasyGIS.NET#109]
I have noticed a weird behavior when the SFmap object is ZOOmed and PANed simultaneously.
It means that the mouse is being pushed around and scrolling the wheel.
There are three shape files.
Polylines and points are in the background, blue rubber line is in the foreground.
This is a GIF animation how it looks like?

![ZOOM AND PAN ISSUE](https://user-images.githubusercontent.com/26789352/226066722-db8fae84-b75c-4885-ac8e-31bc75ced876.gif)

Any idea what might be the reason?

**Comment by dusko23** [comment]
The solution to the above problem was found.
Instead
 SfMap.Refresh(RefreshMode.ForegroundLayers)

SfMap.Refresh(RefreshMode.AllLayers)
should be used.

It appears that the SFmap object does not perform a full refresh when needed.
Zooming to the mouse cursor coordinates probably needs a full refresh by default.

**Comment by wfletcher** [comment]
I can't reproduce this in the Easy GIS .NET desktop application, but it could be because I don't use a combination of foreground and background layers. 

Using the mouse wheel to zoom  - internally the SFMap calculates the new scaling and centre point and then calls SetZoomAnCentre. This method sets the refreshMode to RefreshMode.AllLayers and Invalidates the control

**Comment by dusko23** [comment]
Thanks for the response.
I will probably create a simple, yet full-blown solution to demonstrate the issue and upload it.
Yes, I do use foreground and background layers a lot.
