### ISSUE TITLE
Cyprus EPSG 32636 - Wrong AreaOfUse

### ISSUE THREAD

**Issue by dusko23** [wfletcher/EasyGIS.NET#123]
Running the Cyprus area I just discovered that AreaOfUse exposes the wrong properties.
.
![image](https://github.com/wfletcher/EasyGIS.NET/assets/26789352/f3651fb2-b498-4d34-9fb7-69e00e3a68c0)

**Comment by dusko23** [comment]
Also noticed that that function
**.PixelCoordToGisPoint(New Point(e.X, e.Y))**
returns PointD having both coordinates = **Infinity**
if EPSG is set to 3052

![image](https://github.com/wfletcher/EasyGIS.NET/assets/26789352/82a27cd1-b109-4846-8a51-193fd3ff5eda)

**Comment by wfletcher** [comment]
> Running the Cyprus area I just discovered that AreaOfUse exposes the wrong properties. . ![image](https://user-images.githubusercontent.com/26789352/280487659-f3651fb2-b498-4d34-9fb7-69e00e3a68c0.png)

The Area of Use issue is related to how the library is identifying projections using the proj library. I have fixed this and will be available when I release the next version.

Your second comment appears to be because CRS 3052 is not valid It has been replaced by EPSG 3053 (also not valid( and replaced by EPSG 3057. See https://epsg.io/3052
3052 and 3053 produce the same invalid transformations using QGIS and the transform function on the epsg website I linked
