### ISSUE TITLE
No data loaded into CRS Selection Form

### ISSUE THREAD

**Issue by katterfelto** [wfletcher/EasyGIS.NET#19]
I installed out app on a clean Windows 10 PC and discovered that the CRS Selection form was not populated with CRS data. The Proj6 folder and its contents were present.

After some experimentation I discovered I needed to install the 'Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019'. I think it might be helpful to add redistribution section to the README.md or wiki and list the above as a requirement to save other people having to search for it.

**Comment by wfletcher** [comment]
Thanks for reporting this. There is a ‘runtime_error.txt’ file included in the release download files, but given there was no runtime error reported not surprising it was missed!

As you guessed The redistributable  requirement is because the native proj6 dlls are compiled in MSVC with the runtime dynamically linked.

Anyway  I  will update the readme.md   with a link to the redistributable

**Comment by wfletcher** [comment]
readme.md updated
