### ISSUE TITLE
Concurrent Multiple EPSG Shape Files

### ISSUE THREAD

**Issue by dusko23** [wfletcher/EasyGIS.NET#46]
An issue regarding concurrent multiple EPSG has been detected in my Project.
Explanation:
SFmap object shows two SHP files Easy in GIS.NET Desktop Edition
![image](https://user-images.githubusercontent.com/26789352/159756644-92589f68-61d2-4ed0-a12f-35528b2cfa99.png)
Uk Rivers and Slovene administrative units.
Tooltip in Easy GIS.NET Desktop Edition displays Record info correctly.

The following function in my project
![image](https://user-images.githubusercontent.com/26789352/159757638-3c56ab20-f044-4fab-87d6-424a07226be0.png)
also returns correct Records.

However, the following function
![image](https://user-images.githubusercontent.com/26789352/159758073-0b955283-42d9-44bb-b38b-bfd31b057704.png)
returns UK Records while the mouse is placed over Slovene territory in my project. The thing is that UK coordinate values have similar values to Slovene coordinates.
Observation: Easy GIS.NET Desktop Edition probably does not use the second function.

The first function takes EPSG into account, while the second one does not.
It appears that the second function takes all coordinates (regardless of EPSG) to calculate RecordIndex.
Adding SFmap MapCoordnateSystem as an Optional parameter to the second function might be the solution.

**Comment by dusko23** [comment]
I have successfully solved the above issue.
**GetClosestShape** is called only when the following criteria is met
![image](https://user-images.githubusercontent.com/26789352/159911074-d22e89de-31a0-44f3-baa3-619784846754.png)
This means that the Closest shape is being checked only if Shape File has the same EPSG as SFmap.

**Comment by dusko23** [comment]
However, this will not detect SHPs with different EPSGs.

**Comment by dusko23** [comment]
Using function
![image](https://user-images.githubusercontent.com/26789352/159994702-c1242824-a1dc-4882-8ae2-fc39831b8bfa.png)

does not return **records** if **SFmap** EPSG is different from **SHP** EPSG.
A comment is appreciated.

**Comment by wfletcher** [comment]
The SFMap control uses the following shape find/intersection methods.

For tooltips it uses GetShapeIndexContainingPoint, passing in the MapCoordinateReferenceSystem as the last parameter. GetShapeIndexContainingPoint is faster than GetClosestShape as it will return a record as soon as it meets the search criteria rather than searching all for the closest.

For selecting shapefile records (set the RenderSettings.IsSelectable true) you hold down the ctrl or shift key and drag the mouse. In this case it uses the following functions:
- GetShapeIndiciesIntersectingRect, passing in the MapCoordinateReferenceSystem as the last parameter
- GetShapeIndiciesIntersectingCircle, passing in the MapCoordinateReferenceSystem as the last parameter.

Regarding your previous comment it appears that you are passing in the shapefile's CRS as the last parameter of the function - Unless your map is using the same CRS as your shapefile try using the SFMap.MapCoordinateReferenceSystem as the last parameter.

I would really encourage you to have a look at the SFMap control source code mouse event handling to see how it is performing the shapefile selection and tooltip code.

**Comment by wfletcher** [comment]
On the original question, the ShapeFile.GetClosestShape functions currently expect all coordinate and search parameters to be in the shapefiles coordinate reference system. I will add a sourceCRS parameter like the other functions you mention, but until then you will need to transform your coordinates if they are not in the same CRS as the shapefile before calling the function.

**Comment by dusko23** [comment]
Thanks, Winston for considering adding the source CRS parameter.
Yes, I am already performing all necessary conversions in order to enable
editing multiple shp EPSGs at the same time. It is coming out really well.
Editing SHP files using "SHP remove-and-create-on-the-fly in the
foreground" is a real game enabler. The editing part of GIS is GUI
intensive and I have dug deep into it.
I have created some editing principles not spotted in any other gis system
I know of. Looks really nice.
During editing, everything boils down to removing and creating GUI shp
files on mouse move. If I would use Paint event then loads of functionality
would be lost and new ones must be created on my side.
It would be great if you could avoid creating transformation every time
when shp file with different EPSG to SFmap is added to SFmap.
Best regards,
Dusan

**Comment by wfletcher** [comment]
ShapeFile.GetClosestShape methods now have a parameter to specify the sourceCRS and is available in version 4.8.0

**Comment by dusko23** [comment]
Just perfect :-)
