### ISSUE TITLE
Potential Bug in .GetShapeBounds(i) Detected

### ISSUE THREAD

**Issue by dusko23** [wfletcher/EasyGIS.NET#51]
This is a link to the data I have tested.
[https://api.os.uk/downloads/v1/products/OpenRivers/downloads?area=GB&format=ESRI%C2%AE+Shapefile&redirect](url)
Link represents UK rivers body.  Individual record spans just a small area = boundary rectangle is less than 1000 m in most cases.

If I use **GetShapeBounds** method to get record boundary to check if it fits my target rectangle the following image appears.
![image](https://user-images.githubusercontent.com/26789352/161033785-8f14d4b0-e93d-4e1d-8d80-6411630aefa8.png)
The image was rotated to save web page space.
Please note red records outside Focus Rectangle. **They should not be there.**

If I calculate records Bounds by iterating through all Record Points seeking X,Y Min Max the image is the following.
![image](https://user-images.githubusercontent.com/26789352/161035111-93d0a762-14bf-47f4-96d7-a6b61b0cbe0f.png)
The result is correct.

The final test shows GetShapeBounds instead of records. For better illustrative purposes Focus Rectangle is horizontally oriented.
![image](https://user-images.githubusercontent.com/26789352/161036749-aaa740da-5c4a-4bea-9452-1e55d9acb199.png)
Indicating there might be a bug in **GetShapeBounds** Method. (Actually, it is **GetRecordBounds** Method).
I hope this helps in checking if a bug in the method **GetShapeBounds** exists.

**Comment by wfletcher** [comment]
I have looked into this and cannot reproduce this behavior.

The GetShapeBounds method reads the bounding box directly from the shapefile headers and is not calculated. I have however checked some records in the link above and the bounding box appears correct.

Some screenshots of  some selected records with the bounding box drawn using the RectangleD struct returned form the GetShapeBoundsD method.

![image](https://user-images.githubusercontent.com/12992602/161411860-476c3e5a-9566-40ae-96d8-6a106073aca5.png)

![image](https://user-images.githubusercontent.com/12992602/161411865-8c45ff7f-51e0-41e6-8088-c1033dd3f1ce.png)

![image](https://user-images.githubusercontent.com/12992602/161411870-58195dfb-9cf2-49b6-93d8-4d1670ba1c1d.png)

A couple of things that could explain your observation.
1. The shape bounds are always in the shapefile CRS coordinates. Your map may be using a different CRS.
2. The RectangleD struct used to return the record bounds is derived from the RectangleF struct and has the top and bottom coordinates swapped due to screen positive coordinates being going down. Left and Right are the same

**Comment by dusko23** [comment]
I have conducted a further investigation regarding Boundary Rectangle data.
Above mentioned SHP file has 32 records width boundary height=0.
They are not shown at all. As per #48

Then I created a test where _Boundary Rectangle created from Headers_ **"falls"** inside my **Focus Rectangle** but _Boundary Rectangle calculated seeking Min Max values from Record points_ **does not**.

This is the result
![image](https://user-images.githubusercontent.com/26789352/161450973-f29703fd-8c87-4176-8717-d6e5c4d62001.png)

Fucus Rectangle is not populated which is correct :-)

However, this indicates that the original Ordnance Survey Waterbody SHP file has incorrect Header Boundary Rectangle (Box) Data. 
Can you please check if my Assumption is correct?

**Comment by wfletcher** [comment]
From my tests I did not see any issues with the shapefile and record bounds look correct. I did not check every record - if you want to do this you would need to write a program to calculate the bounding box for each record you can call GetShapeDataD(recordnumber), calculate the bounding box and compare to GetShapeBoundsD(recordnumber)
