### ISSUE TITLE
SHP CoordinateReferenceSystem is Nothing

### ISSUE THREAD

**Issue by dusko23** [wfletcher/EasyGIS.NET#58]
Just discovered
![image](https://user-images.githubusercontent.com/26789352/164335360-06cb704a-61a7-476f-847d-0c6955fea382.png)

Here is an example of a shapefile.
[HP51.zip](https://github.com/wfletcher/EasyGIS.NET/files/8525836/HP51.zip)
Shapefile extracted from here:
[https://osdatahub.os.uk/downloads/open/Terrain50](https://osdatahub.os.uk/downloads/open/Terrain50)

But CRS is recognized if this prj file is used. Rename txt to prj.
[WatercourseLink.txt](https://github.com/wfletcher/EasyGIS.NET/files/8525867/WatercourseLink.txt)

It appears that Ordnance Survey is using different prj files (which is not good).
However, is it possible to somehow deduct CRS from the "crippled" prj file?

**Comment by dusko23** [comment]
Another test importing SHP file when OpenStreet map defines SFmap map coordinate system.
Shapefile displays OK.
![image](https://user-images.githubusercontent.com/26789352/164338015-10eaf7d7-4a3c-4b8f-91ac-4cc85f746827.png)
It probably means that CoordinateReferenceSystem and Authority are known to the internal structure of the SFmap object.
Otherwise, the shapefile could not be drawn correctly on SFmap when CRS is PseudoMercator.

**Comment by wfletcher** [comment]
The prj file is read correctly, however it cannot be identified due to the parameters differing from what is in the proj database. The shapefile CoordinateReferenceSystem is not null/Nothing, only the Id as it cannot be identified with confidence.

From what I can see the issue is due to rounding in the "Scale_Factor" parameter, which results in about a 1mm difference from the scale factor parameter of EPSG 27700.

When a projection file is read the proj_9_0 library uses a confidence level to identify the known CRS from the database. The default confidence level is 70 (same level used by QGIS). If you want to change it to identify the prj file in your example shapefile you can change the confidence level to the following, however I would not recommend this as a level of 25 is very low.
 
((CoordinateReferenceSystemFactory)EGIS.Projections.CoordinateReferenceSystemFactory.Default).IdentificationConfidenceThreshold = 25;

**Comment by wfletcher** [comment]
Just to clarify - EGIS will read and use any CRS defined in the .prj file. If it cannot be identified it can still use the CRS and transform to another CRS.

**Comment by dusko23** [comment]
Thanks for that. I am using CRS Id to check if I need to do transformations (editing under different CRS).
Is there any other way to check if SFmap and SHP Coordinate systems are different?
Currently I am using
![image](https://user-images.githubusercontent.com/26789352/164434611-db26cd68-a373-47e6-8156-804ff0eec634.png)

**Comment by wfletcher** [comment]
Use the IsEquivalent method.

sourceCRS.IsEquivalent(targetCRS)

**Comment by dusko23** [comment]
Thanks, works like magic :-)
