### ISSUE TITLE
Heatmap - Not a issue, just searching a way

### ISSUE THREAD

**Issue by theo2f** [wfletcher/EasyGIS.NET#67]
Hi guys.
I need to create a heatmap. Can you suggest a way to do this?
Create images for each point and put them on map is a way, but I want to know if have a better option.

Something like this
![image](https://user-images.githubusercontent.com/5304192/172187171-03b713df-2277-444b-9f46-90d4ce6eabdb.png)

Thank you!

**Comment by dusko23** [comment]
A description of the data structure representing the heat map is needed to provide a relevant answer.
Like PNG bitmap, cloud points, polygons,...
Depending on the answer I can give some ideas.

**Comment by theo2f** [comment]
I have a list of coordinates where certain events occur.
I need to create a heatmap to demonstrate where these events most often occur.

**Comment by theo2f** [comment]
Sorry @dusko23 for a poor information that I send.

Well, I have a list with all points. Points may overlap.
The illustration of the list is something like this:
![image](https://user-images.githubusercontent.com/5304192/172471879-6cb0e35e-2d71-4670-a7fc-5cf0d74ae61f.png)

**Comment by dusko23** [comment]
OK, but these are still individual points. How do you know which points span (belong to) a particular heatmap?
Or does each point represent a heatmap value to be colored by a matching color?
Would you like to color a circle around a point with a color that will start slowly fading from the circle center?
How would you define radius?
Or would you like to use different semitransparent colors while moving from the center to the circle border where coloring ends?
Or would you like to join relevant points together to create heatmap data and draw a heatmap based on points density in a group? 
How far should the individual heatmap span if it is defined by a group of points?

**Comment by theo2f** [comment]
Eu pensei inicialmente em usar uma imagem como essa (porém com fundo transparente) e adicionar como um mapa de pontos, usando as coordenadas e a imagem como ícone.
![image](https://user-images.githubusercontent.com/5304192/172478358-f5b5c242-3bbb-4a8f-a1ce-a570a530def4.png)

Porém, o resultado ficaria como abaixo, não destacando o vermelho:
![image](https://user-images.githubusercontent.com/5304192/172478792-8c5f435f-1a2f-44ad-9fc7-d584023648b4.png)

_OK, but these are still individual points. How do you know which points span (belong to) a particular heatmap?_
Answer: I don't know. I just have individual points and no reference.

_Or does each point represent a heatmap value to be colored by a matching color?_
Answer: No.

_Would you like to color a circle around a point with a color that will start slowly fading from the circle center?
How would you define radius?
Or would you like to use different semitransparent colors while moving from the center to the circle border where coloring ends?_
Answer: It was my test, but the format I used doesn't give a good result.

_Or would you like to join relevant points together to create heatmap data and draw a heatmap based on points density in a group?_
Answer: That seems to me the most appropriate

_How far should the individual heatmap span if it is defined by a group of points?_
Answer: Honestly I don't know how to divide these groups. Perhaps the distance.

**Comment by dusko23** [comment]
OK, here is how would I do it.
The most intriguing part is grouping points together to form individual heat maps.

**Logical steps:**
Select a radius that will be used to connect relevant points together.
Here is an example - just for demonstration purposes.
![image](https://user-images.githubusercontent.com/26789352/172482537-cca955af-96ef-4ab2-ac37-7af3d0ef93a5.png)

Each joined group represents a source to create a heatmap.

Convert to black and white.
![image](https://user-images.githubusercontent.com/26789352/172483220-e7a5aa26-ff01-4e4f-a1b3-2d042eb0cb5c.png)

**IMPLEMENTATION USING SFmap Library and combining with potrace runs.**
To create a black and white bitmap draw points shape with specified radius and paint points in black.
Save bitmap as image.
Save corner coordinates!

Use potrace.exe [http://potrace.sourceforge.net/](url) and run it inside your application to get a perfect vectorized outline of each group. Map result coordinates in pixels to your real corner coordinates.
Create a  shapefiles where each group will be represented by a polyline (not a polygon).

Now start drawing closed polylines increasing pen width and saving bitmaps.
Run potrace for each of these bitmaps. 
You will start getting boundaries you are looking for.
Remap each potrace result in pixels to your corner coordinates of a bitmap.
Create polygons with holes for each step (if you would like to use transparency). Otherwise, holes are not needed.
Use a custom renderer to color them. Like the first iteration is red, next orange, and all down to light yellow.
Draw in reverse order. Outmost first, center the last.
Experiment with the initial radius and radius in consecutive steps.
You will end up with a fine heatmap.
To make life easier work with the individual group only to avoid overlapping during the process. But always use the same area.
Color only the group in focus with black. The rest are white.

My experience is that this kind of approach gives very good results and it is easy to debug and manage.
It can be 100% automated and you will just be changing the radius and observing results. In seconds or less :-)
Just running ShapeFile lib and potrace in a loop.
If you would go for a pure vector approach, like calculating buffers around polylines you would be looking for a lot of trouble.
P.S. I will probably implement a similar approach to create a heatmap for any collection of points.
If the average value of the points representing group seeds is higher then the first ring will be colored with a more intensive color.

**Comment by wfletcher** [comment]
I would recommend looking at a c# heatmap library. There are probably many out there, but this library is written in C# and will probably offer what you want.
https://github.com/RainkLH/HeatMapSharp

You will need to generate the heatmapImage whenever the SFMap is zoomed or panned and then add a paint event handler to the SFMap to overlay the heatmapimage. 

The HeatMapImage class expects DataType coordinates to be in pixel coordinates so you will need to iterate over the shapefile record points and convert to pixel coordinates.

I had a quick look at this library and it seems to have reasonable performance for ~25000 points.

**Comment by wfletcher** [comment]
Here's an example using the library.
[HeatmapDemo.zip](https://github.com/wfletcher/EasyGIS.NET/files/8857761/HeatmapDemo.zip)

You will need to restore nuget packages if VS doesn't automatically.  Add a "point" shapefile to the form to display the heatmap

**Comment by dusko23** [comment]
Oh, **Clean Solution** button did the magic :-)
I compiled and run.
Imported SHP file.
Nothing happened after a while.
Picture is the same.
![image](https://user-images.githubusercontent.com/26789352/172672236-b3849ad3-f315-4a54-b143-dd51c27549e9.png)

I have saved bitmap from Paint event
![image](https://user-images.githubusercontent.com/26789352/172672458-6b5104b1-20ad-4c69-9a4d-8c87417e1212.png)

But it has no content.
![image](https://user-images.githubusercontent.com/26789352/172672627-bea93177-0939-4dc7-8ea3-5f2ab73400cf.png)

Any idea?

**Comment by theo2f** [comment]
I did two things to run:

1. Removed and installed EGIS NuGet packages;
2. I changed the Paint() method, including a is null check (to avoid errors when shapefiles can't load or is not a Point Shapefile type).
![image](https://user-images.githubusercontent.com/5304192/172678628-dbf59153-4b49-4444-98ad-f8222ac8c2f8.png)

**Comment by theo2f** [comment]
> I tried to run Demo at my end to compare with a future solution that will create colored SHP donut type polygons with transparency in order to see topographic/aerial/lidar mapping in the background.

I'll appreciate your code when it's being done! Share please.

**Comment by wfletcher** [comment]
This is what it should look like. @dusko23 no idea why your bitmap is empty. Try playing with the sigma value.
![image](https://user-images.githubusercontent.com/12992602/172731182-25a83c99-5d95-4ef6-99fe-67a1b8f66509.png)

**Comment by wfletcher** [comment]
@dusko23  Make sure the map CRS is the same as the shapefile.
![image](https://user-images.githubusercontent.com/12992602/172744298-bc928875-63c5-41ae-a931-132596e8edab.png)

**Comment by dusko23** [comment]
Yes, that cured the issue  :-) Thanks.
I found an interesting effect that does not seem right.
Heatmap heavily depends on the points distributed inside visible extent.
Here are screen shots while mowing a map towards Nort East.
![image](https://user-images.githubusercontent.com/26789352/172749250-aff06fea-ade9-4dd2-abf8-5ec41b034612.png)
![image](https://user-images.githubusercontent.com/26789352/172749298-f469178a-1ab8-4271-b497-36998af49481.png)
![image](https://user-images.githubusercontent.com/26789352/172749329-ece36870-5828-4f0d-87bf-dc0df5e9afe9.png)
![image](https://user-images.githubusercontent.com/26789352/172749377-213e0cff-0158-4398-bf00-3c840b505865.png)
![image](https://user-images.githubusercontent.com/26789352/172749413-f5783ec0-b2df-4e4e-b256-7778d5746b00.png)
![image](https://user-images.githubusercontent.com/26789352/172749542-88a90142-de8c-41be-b39d-afdb1ec652af.png)

However, the effect is compatible with Wayne Dyer's saying: "If you change the way you look at things, the things you look at change."

**Comment by wfletcher** [comment]
I didn't write the HeatMap class - it is copied from here:
https://github.com/RainkLH/HeatMapSharp

Heatmaps are used to visualize the density of points and it appears that the calculations in this implementation only use points that are within the visible area.
