### ISSUE TITLE
Wind directions - Not a issue, just searching a way

### ISSUE THREAD

**Issue by theo2f** [wfletcher/EasyGIS.NET#69]
Hi guys.

I want to put wind information on map. Something like this:
![image](https://user-images.githubusercontent.com/5304192/172188547-61b9e10f-2943-4a2e-b8ca-72c57a9b2a20.png)

Someone already did this before?
I think that I'll need a Point Shapefile, but I don't know how I'll do the rotation for each icon.

Thank you!

**Comment by dusko23** [comment]
I suggest using 2 vertex polylines and making the direction arrow visible to True.
The direction will appear in the middle.
![image](https://user-images.githubusercontent.com/26789352/173163245-dd0a27a4-883c-43f5-9f94-280e20435c27.png)

You could also take a font and use an arrow glyph and label 2 vertex polylines with that "arrow" value.
To get rid of polyline in non-selection mode make it transparent.
Here is an example of the Wolf glyph rotated as needed.
Note selection line.
![image](https://user-images.githubusercontent.com/26789352/173163537-ed131a3c-df7c-4161-aa64-6f5d9641bf9f.png)

And placed on the map and not selected anymore.
![image](https://user-images.githubusercontent.com/26789352/173163571-4fd7a786-ce3f-411e-94de-b12148170aa2.png)
You need to define Font in Points. NOT in pixels.

You could use a raster icon and have the 360 icon prefabricated but I don't recommend that because it does not look good for your type of scenario.

You could also suggest Winston to create an option to put arrow placement at the end of the polyline leg.

**Comment by wfletcher** [comment]
If you have a point shape file with a wind direction attribute the best way to do this is probably to just add a paint event handler and draw the arrows. Calculating the "rotation" is just simple trigonometry, where the x component is cos(angle) and the y component is sin(angle).


```
               /// <summary>
		/// Draws a direction arrow
		/// </summary>
		/// <param name="g">Graphics object</param>
		/// <param name="pen">Arrow pen</param>
		/// <param name="pt">The pixel location of the arrow</param>
		/// <param name="heading">The heading direction</param>
		/// <param name="arrowLength">The length of the arrow</param>
		/// <remarks>
		/// <para>The heading is a standard heading in degrees, where North is zero, East is 90, South is 180, West is 270</para>
		/// </remarks>
		private void DrawDirectionArrow(Graphics g, Pen pen, Point pt, double heading, int arrowLength)
		{
			//convert heading to angle
			double angle = (90 - heading) * Math.PI/180;

			double dx = Math.Cos(angle);
			double dy = Math.Sin(angle);

			Point pt2 = new Point(pt.X + (int)Math.Round(dx * arrowLength), pt.Y + (int)Math.Round(dy * arrowLength));

			g.DrawLine(pen, pt, pt2);

		}

//inside paint event handler..

using (EGIS.Projections.ICoordinateTransformation transform = EGIS.Projections.CoordinateReferenceSystemFactory.Default.CreateCoordinateTrasformation(shapeFile.CoordinateReferenceSystem, sfMap1.MapCoordinateReferenceSystem))
			{
				using (Pen arrowPen = new Pen(Color.Blue, 2))
				{
					arrowPen.CustomEndCap = new System.Drawing.Drawing2D.AdjustableArrowCap(3, 6);
					for (int n = 0; n < shapeFile.RecordCount; ++n)
					{
						PointD pt = shapeFile.GetShapeDataD(n)[0][0];
						pt = transform.Transform(pt);

						Point pixel = sfMap1.GisPointToPixelCoord(pt);

						if (pixel.X >= 0 && pixel.Y >= 0 && pixel.X < sfMap1.ClientSize.Width && pixel.Y < sfMap1.ClientSize.Height)
						{
							string[] attributes = shapeFile.GetAttributeFieldValues(n);
							string directionAttribute = attributes[headingFieldIndex];
							double heading;
							if (double.TryParse(directionAttribute, System.Globalization.NumberStyles.Float, System.Globalization.CultureInfo.InvariantCulture, out heading))
							{
								DrawDirectionArrow(g, arrowPen, pixel, heading, 30);
							}
						}
					}
				}
			}

```

**Comment by theo2f** [comment]
Thank you guys!

**Comment by dusko23** [comment]
Hi, start with angle = 0. You need to get a horizontal line with an arrow on the right. You are working on 2D math here. True north is at about mathematical 90 degrees. Depening on SFmap EPSG code.
Inject your own angle parameters first in order to get math working :-) 
Like 0, 90, 180, and 270 degrees.
My general suggestion would be to ask Winston to add one parameter more to Arrow parameters. Like position middle, end or start. I suggested adding a parameter to draw an arrow at every n-th position on a polyline (to enable nice contours labeling).

Regarding your attempt to use Paint Event I would suggest sticking with Winston library and leaving Paint event for the moments that have nothing to do with your shape files.  Like drawing CrossHair on mouse move.
You never know where your wind direction will evolve and it might happen that at some point you will be using two engines to draw your shape files. Winstons and yours.

**Comment by wfletcher** [comment]
Sorry there was a bug in my DrawDirectionArrow method - my calculation was for Cartesian coordinates and I forgot that in screen coordinates positive y goes down.
```
        private void DrawDirectionArrow(Graphics g, Pen pen, Point pt, double heading, int arrowLength)
        {
            //convert heading to angle
            double angle = (90 - heading) * Math.PI / 180;

            double dx = Math.Cos(angle);
            //dy is negative as positive y direction is down in screen coordinates
            double dy = -Math.Sin(angle);

            Point pt2 = new Point(pt.X + (int)Math.Round(dx * arrowLength), pt.Y + (int)Math.Round(dy * arrowLength));
            g.DrawLine(pen, pt, pt2);
        }
```

**Comment by theo2f** [comment]
The math does not forgive... Just a signal and it solved the problem.
Thank you very much!
