### ISSUE TITLE
Two Minor Bugs

### ISSUE THREAD

**Issue by dusko23** [wfletcher/EasyGIS.NET#97]
- The SFmap object does not retain the design time property BorderStyle.None and must be set in code.
- If RendederSetting.Font is not defined then Sfmap.refresh(True) crashes.

**Comment by wfletcher** [comment]
The first issue seems to be because I set the border style when the SFMap is created. This property is defined in the base class hierarchy  with a default property of None and it appears the VS designer does not set the property value if it is the default BorderControl.None. I will fix this in next release.

The RenderSettings.Font issue is a bug in the calling code. If Attempting to draw labels and Font is null then an exception will be generated. I will consider detecting the null font if an attempt is made to draw a label but I’ll still throw an exception with a message indicating why or users will not know why the labels are not drawn.
